//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoetryBook.Content.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoetryBook.Content.lang.eng", typeof(eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string strAdminPanel {
            get {
                return ResourceManager.GetString("strAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have already account.
        /// </summary>
        public static string strAlreadyAccount {
            get {
                return ResourceManager.GetString("strAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string strBirthDate {
            get {
                return ResourceManager.GetString("strBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string strCategories {
            get {
                return ResourceManager.GetString("strCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string strCategory {
            get {
                return ResourceManager.GetString("strCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Management.
        /// </summary>
        public static string strCategoryManagement {
            get {
                return ResourceManager.GetString("strCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string strComplete {
            get {
                return ResourceManager.GetString("strComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string strConfirm {
            get {
                return ResourceManager.GetString("strConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string strCreateAcc {
            get {
                return ResourceManager.GetString("strCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string strCreateAccount {
            get {
                return ResourceManager.GetString("strCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string strDeleteUser {
            get {
                return ResourceManager.GetString("strDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string strFemale {
            get {
                return ResourceManager.GetString("strFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string strGender {
            get {
                return ResourceManager.GetString("strGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installement.
        /// </summary>
        public static string strInstall {
            get {
                return ResourceManager.GetString("strInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string strLangText {
            get {
                return ResourceManager.GetString("strLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string strLogOut {
            get {
                return ResourceManager.GetString("strLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string strMail {
            get {
                return ResourceManager.GetString("strMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Admin.
        /// </summary>
        public static string strMakeAdmin {
            get {
                return ResourceManager.GetString("strMakeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Normal.
        /// </summary>
        public static string strMakeNormal {
            get {
                return ResourceManager.GetString("strMakeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string strMale {
            get {
                return ResourceManager.GetString("strMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the birth date.
        /// </summary>
        public static string strMsgBirthDate {
            get {
                return ResourceManager.GetString("strMsgBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Mail.
        /// </summary>
        public static string strMsgEnterMail {
            get {
                return ResourceManager.GetString("strMsgEnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your nick.
        /// </summary>
        public static string strMsgNick {
            get {
                return ResourceManager.GetString("strMsgNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password.
        /// </summary>
        public static string strMsgPassword {
            get {
                return ResourceManager.GetString("strMsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the security code.
        /// </summary>
        public static string strMsgSecurityCode {
            get {
                return ResourceManager.GetString("strMsgSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First And Last Name.
        /// </summary>
        public static string strNameAndSurname {
            get {
                return ResourceManager.GetString("strNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string strNick {
            get {
                return ResourceManager.GetString("strNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poet.
        /// </summary>
        public static string strPoet {
            get {
                return ResourceManager.GetString("strPoet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poet Management.
        /// </summary>
        public static string strPoetManagement {
            get {
                return ResourceManager.GetString("strPoetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetries.
        /// </summary>
        public static string strPoetries {
            get {
                return ResourceManager.GetString("strPoetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        public static string strPoetry {
            get {
                return ResourceManager.GetString("strPoetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry Management.
        /// </summary>
        public static string strPoetryManagement {
            get {
                return ResourceManager.GetString("strPoetryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poets.
        /// </summary>
        public static string strPoets {
            get {
                return ResourceManager.GetString("strPoets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me!.
        /// </summary>
        public static string strRememberMe {
            get {
                return ResourceManager.GetString("strRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string strSecurityCode {
            get {
                return ResourceManager.GetString("strSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string strSelectLang {
            get {
                return ResourceManager.GetString("strSelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string strUserManagement {
            get {
                return ResourceManager.GetString("strUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Mail.
        /// </summary>
        public static string sttrAdminMail {
            get {
                return ResourceManager.GetString("sttrAdminMail", resourceCulture);
            }
        }
    }
}
