//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoetryBook.Content.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoetryBook.Content.lang.tr", typeof(tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        internal static string strAdminPanel {
            get {
                return ResourceManager.GetString("strAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabım Var.
        /// </summary>
        internal static string strAlreadyAccount {
            get {
                return ResourceManager.GetString("strAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        internal static string strBirthDate {
            get {
                return ResourceManager.GetString("strBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        internal static string strCategories {
            get {
                return ResourceManager.GetString("strCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string strCategory {
            get {
                return ResourceManager.GetString("strCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Yönetimi.
        /// </summary>
        internal static string strCategoryManagement {
            get {
                return ResourceManager.GetString("strCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamla.
        /// </summary>
        internal static string strComplete {
            get {
                return ResourceManager.GetString("strComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string strConfirm {
            get {
                return ResourceManager.GetString("strConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hesap Oluştur.
        /// </summary>
        internal static string strCreateAcc {
            get {
                return ResourceManager.GetString("strCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string strCreateAccount {
            get {
                return ResourceManager.GetString("strCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyı Sil.
        /// </summary>
        internal static string strDeleteUser {
            get {
                return ResourceManager.GetString("strDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        internal static string strFemale {
            get {
                return ResourceManager.GetString("strFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        internal static string strGender {
            get {
                return ResourceManager.GetString("strGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum.
        /// </summary>
        internal static string strInstall {
            get {
                return ResourceManager.GetString("strInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string strLangText {
            get {
                return ResourceManager.GetString("strLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string strLogOut {
            get {
                return ResourceManager.GetString("strLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string strMail {
            get {
                return ResourceManager.GetString("strMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Yap.
        /// </summary>
        internal static string strMakeAdmin {
            get {
                return ResourceManager.GetString("strMakeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Üye Yap.
        /// </summary>
        internal static string strMakeNormal {
            get {
                return ResourceManager.GetString("strMakeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        internal static string strMale {
            get {
                return ResourceManager.GetString("strMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi Gir.
        /// </summary>
        internal static string strMsgBirthDate {
            get {
                return ResourceManager.GetString("strMsgBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresini Gir.
        /// </summary>
        internal static string strMsgEnterMail {
            get {
                return ResourceManager.GetString("strMsgEnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı Gir.
        /// </summary>
        internal static string strMsgNick {
            get {
                return ResourceManager.GetString("strMsgNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolanı Gir.
        /// </summary>
        internal static string strMsgPassword {
            get {
                return ResourceManager.GetString("strMsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodunu Gir.
        /// </summary>
        internal static string strMsgSecurityCode {
            get {
                return ResourceManager.GetString("strMsgSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string strNameAndSurname {
            get {
                return ResourceManager.GetString("strNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string strNick {
            get {
                return ResourceManager.GetString("strNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şair.
        /// </summary>
        internal static string strPoet {
            get {
                return ResourceManager.GetString("strPoet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şair Yönetimi.
        /// </summary>
        internal static string strPoetManagement {
            get {
                return ResourceManager.GetString("strPoetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şiirler.
        /// </summary>
        internal static string strPoetries {
            get {
                return ResourceManager.GetString("strPoetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şiir.
        /// </summary>
        internal static string strPoetry {
            get {
                return ResourceManager.GetString("strPoetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şiir Yönetimi.
        /// </summary>
        internal static string strPoetryManagement {
            get {
                return ResourceManager.GetString("strPoetryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şairler.
        /// </summary>
        internal static string strPoets {
            get {
                return ResourceManager.GetString("strPoets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        internal static string strRememberMe {
            get {
                return ResourceManager.GetString("strRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        internal static string strSecurityCode {
            get {
                return ResourceManager.GetString("strSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seç.
        /// </summary>
        internal static string strSelectLang {
            get {
                return ResourceManager.GetString("strSelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        internal static string strUserManagement {
            get {
                return ResourceManager.GetString("strUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin E-Posta.
        /// </summary>
        internal static string sttrAdminMail {
            get {
                return ResourceManager.GetString("sttrAdminMail", resourceCulture);
            }
        }
    }
}
