//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoetryBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoetryBookDbEntities : DbContext
    {
        public PoetryBookDbEntities()
            : base("name=PoetryBookDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbcategory> tbcategories { get; set; }
        public virtual DbSet<tbcomment> tbcomments { get; set; }
        public virtual DbSet<tbmember> tbmembers { get; set; }
        public virtual DbSet<tbpoet> tbpoets { get; set; }
        public virtual DbSet<tbpoetry> tbpoetries { get; set; }
    }
}
