//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoetryBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmember()
        {
            this.tbcomments = new HashSet<tbcomment>();
        }
    
        public int memberID { get; set; }
        public string nick { get; set; }
        public string nameandsurname { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string gender { get; set; }
        public string accounttype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcomment> tbcomments { get; set; }
    }
}
