//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoetryBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpoetry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbpoetry()
        {
            this.tbcomments = new HashSet<tbcomment>();
        }
    
        public int poetryID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int poetidsof { get; set; }
        public int catidsof { get; set; }
    
        public virtual tbcategory tbcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcomment> tbcomments { get; set; }
        public virtual tbpoet tbpoet { get; set; }
    }
}
